frr version 8.4_git
frr defaults traditional
hostname pe2
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth2
 ip address 10.2.12.1/30
exit
!
interface eth3
 ip address 10.2.14.1/30
exit
!
interface eth1
 ip address 10.0.2.2/24
 ip ospf area 0
 mpls
exit
!
interface lo
 ip address 3.3.3.3/32
 ip ospf area 0
exit
!
router bgp 65000
 bgp router-id 3.3.3.3
 no bgp default ipv4-unicast
 neighbor 1.1.1.1 remote-as 65000
 neighbor 1.1.1.1 update-source lo
 !
 address-family ipv4 vpn
  neighbor 1.1.1.1 activate
 exit-address-family
exit
!
router bgp 65000 vrf CUST
 bgp router-id 10.2.12.1
 no bgp ebgp-requires-policy
 neighbor 10.2.12.2 remote-as 65102
 neighbor 10.2.14.2 remote-as 65104
 !
 address-family ipv4 unicast
  label vpn export auto
  rd vpn export 65000:1
  rt vpn both 65000:1
  export vpn
  import vpn
 exit-address-family
exit
!
router ospf
 ospf router-id 3.3.3.3
 mpls ldp-sync
exit
!
mpls ldp
 router-id 3.3.3.3
 !
 address-family ipv4
  discovery transport-address 3.3.3.3
  !
  interface eth1
  exit
  !
 exit-address-family
 !
exit
!
