frr version 8.4_git
frr defaults traditional
hostname p1
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.1.2/24
 ip ospf area 0
 mpls
exit
!
interface eth2
 ip address 10.0.2.1/24
 ip ospf area 0
 mpls
exit
!
interface lo
 ip address 2.2.2.2/32
 ip ospf area 0
exit
!
router ospf
 ospf router-id 2.2.2.2
 mpls ldp-sync
exit
!
mpls ldp
 router-id 2.2.2.2
 !
 address-family ipv4
  discovery transport-address 2.2.2.2
  !
  interface eth1
  exit
  !
  interface eth2
  exit
  !
 exit-address-family
 !
exit
!
