frr version 8.4_git
frr defaults traditional
hostname pe1
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth2
 ip address 10.1.11.1/30
exit
!
interface eth3
 ip address 10.1.13.1/30
exit
!
interface eth1
 ip address 10.0.1.1/24
 ip ospf area 0
 mpls
exit
!
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0
exit
!
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp default ipv4-unicast
 neighbor 3.3.3.3 remote-as 65000
 neighbor 3.3.3.3 update-source lo
 !
 address-family ipv4 vpn
  neighbor 3.3.3.3 activate
 exit-address-family
exit
!
router bgp 65000 vrf CUST
 bgp router-id 10.1.11.1
 no bgp ebgp-requires-policy
 neighbor 10.1.11.2 remote-as 65101
 neighbor 10.1.13.2 remote-as 65103
 !
 address-family ipv4 unicast
  label vpn export auto
  rd vpn export 65000:1
  rt vpn both 65000:1
  export vpn
  import vpn
 exit-address-family
exit
!
router ospf
 ospf router-id 1.1.1.1
 mpls ldp-sync
exit
!
mpls ldp
 router-id 1.1.1.1
 !
 address-family ipv4
  discovery transport-address 1.1.1.1
  !
  interface eth1
  exit
  !
 exit-address-family
 !
exit
!
